library(shinytest2)

test_that("{shinytest2} recording: shiny", {
  app <- AppDriver$new(name = "shiny", height = 1232, width = 1622)
  app$set_inputs(tabs = "import_data")
  app$click("input-load_example_data")
  app$set_inputs(main_tabs_tables = "compliance_tab")
  app$set_inputs(main_tabs_tables = "filtering_tab")
  app$set_inputs(main_tabs_tables = "annotation_tab")
  app$set_inputs(main_tabs_tables = "sleep_regularity_tab")
  app$set_inputs(main_tabs_plots = "Sleep Spiral")
  app$set_inputs(main_tabs_plots = "Sleep Onset & Wakeup")
  app$set_inputs(`bedtimes_waketimes-groupby` = "weekday")
  app$set_inputs(`bedtimes_waketimes-groupby` = "workday")
  app$set_inputs(main_tabs_plots = "Sleep Times Distributions")
  app$set_inputs(`sleep_distributions-plot_type` = "Histogram")
  app$set_inputs(`sleep_distributions-binwidth` = 0.25)
  app$set_inputs(`sleep_distributions-plot_type` = "Density")
  app$set_inputs(`sleep_distributions-circular` = TRUE)
  app$set_inputs(main_tabs_plots = "Sleep Bubbles")
  app$set_inputs(`sleep_bubbles-colorby` = "is_workday")
  app$set_inputs(main_tabs_plots = "Hypnogram")
  app$set_inputs(main_tabs_plots = "Session Timeseries")
  app$set_inputs(main_tabs_plots = "Epoch Timeseries")
  app$set_inputs(tabs = "filtering")
  app$set_inputs(main_tabs_plots = "Sleep Clock")
  app$set_inputs(`filtering-time_in_bed` = 2)
  app$set_inputs(`filtering-time_range` = c("2", "12"))
  app$set_inputs(`filtering-time_range` = c("13", "12"))
  app$set_inputs(`filtering-date_range` = c("2025-04-07", "2025-04-17"))
  app$set_inputs(`filtering-date_range` = c("2025-04-07", "2025-04-11"))
  app$set_inputs(tabs = "export_data")
  app$expect_download("export_data-download_sessions")
  app$expect_download("export_data-download_epochs")
  app$set_inputs(`export_data-title` = "test")
  app$expect_download("export_data-download_report")
})
